name: "homebrew-import-release"
description: "Create a Homebrew formula from a Github release"
branding:
  icon: "git-pull-request"
  color: "blue"
inputs:
  template:
    description: "Local path to the template"
    required: true
  target:
    description: "Target path for the formula"
    required: true
  repository:
    description: "Repository providing the formula template and the Github release"
    required: true
  asset-selector:
    description: "Substring that's used to find the asset to include in the formula"
    required: true
  alt-asset-selector:
    description: "Substring that's used to find the alternative asset (e.g. a Linux artifact) to include in the formula"
    required: false
  tag:
    description: "Release tag (defaults to latest)"
    required: false
  version:
    description: >
      Version of the Homebrew formula (defaults to release tag without potential
      `v` prefix)
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.template }}
    - ${{ inputs.target }}
    - ${{ inputs.repository }}
    - ${{ inputs.asset-selector }}
    - ${{ inputs.alt-asset-selector }}
    - ${{ inputs.tag }}
    - ${{ inputs.version }}
