name: "homebrew-import-release"
description: "Create a Homebrew formula from a Github release"
branding:
  icon: "git-pull-request"
  color: "blue"
inputs:
  target:
    description: "Target path for the formula"
    required: true
  repository:
    description: "Repository providing the formula template and the Github release"
    required: true
  templateRef:
    description: "Ref (branch/tag/commit) to use for the template lookup"
    required: true
    default: "master"
  tag:
    description: "Release tag (defaults to latest)"
    required: false
  version:
    description: >
      Version of the Homebrew formula (defaults to release tag without potential
      `v` prefix)
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.target }}
    - ${{ inputs.repository }}
    - ${{ inputs.tag }}
    - ${{ inputs.version }}
    - ${{ inputs.templateRef }}
