name: CI

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          target: into-docker.rb
          repository: into-docker/into-docker
          selector: macos-amd64.zip
          alt-selector: linux-amd64.zip
      - run: cat into-docker.rb
