name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          target: into-docker.rb
          version: 1.0.0
          repository: into-docker/into-docker
          tag: v1.0.0
      - run: cat into-docker.rb
